name: root_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3  # Keep this
  flutter_dotenv: ^5.0.2  # Keep this
  http: ^0.13.4  # Keep this
  
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpeg
    - assets/4.webp
    - assets/5.jpeg
    - assets/6.jpeg
    - assets/7.webp
    - assets/8.jpg
    - assets/9.jpg
    - assets/10.png
    - assets/11.jpg
    - assets/logo.svg  # Keep this
    - assets/folder.svg  # Keep this
