name: root_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3  # Keep this
  flutter_dotenv: ^5.2.1  # Keep this
  http: ^0.13.4  # Keep this
  
  receive_sharing_intent: ^1.8.1
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  http_mock_adapter: ^0.2.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/logo.svg  # logo
    - assets/folder.svg  # folder 모양 svg
    
    - assets/mock_data.json # 임시데이터 items listz

    - assets/image.png 
    - assets/image2.png 

    - assets/scroll.svg # 스크롤바 이미지

    - assets/Link.svg